/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.54
 * Generated at: 2014-10-07 04:46:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.phr.html;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class _001test_005floginmain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <title>å¥åº·ç®¡çæ¯æ´ãµã¼ãã¹</title>\r\n");
      out.write("    <meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("\t<meta name=\"format-detection\" content=\"telephone=no\">\r\n");
      out.write("\t<meta http-equiv=\"description\" content=\"this is my page\">\r\n");
      out.write("\t<meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"../jquery/css/jquery.mobile-theme.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"../css/common.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"../css/font-awesome.min.css\">\r\n");
      out.write("\t<script src=\"../jquery/js/jquery.js\"></script>\r\n");
      out.write("\t<script src=\"../jquery/js/jquery.mobile-1.3.2.min.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t$.mobile.buttonMarkup.hoverDelay = \"false\";\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(document).on('blur', 'input, textarea', function() {\r\n");
      out.write("\t\t    setTimeout(function() {\r\n");
      out.write("\t\t        window.scrollTo(document.body.scrollLeft, document.body.scrollTop);\r\n");
      out.write("\t\t    }, 0);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body>\r\n");
      out.write("  \t<div data-role=\"page\" id=\"login-page\" data-theme=\"c\"\r\n");
      out.write("\t\tdata-url=\"login-page\">\r\n");
      out.write("\t\t<div data-role=\"header\" data-theme=\"g\" data-tap-toggle=\"false\" data-position=\"fixed\"\r\n");
      out.write("\t\t\tid=\"header\" class=\"jqm-header\">\r\n");
      out.write("\t\t\t<h1 style=\"margin-left:10px;\">å¥åº·ç®¡çæ¯æ´ãµã¼ãã¹</h1>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("   \t\t<div data-role='content'>\r\n");
      out.write("  \t\t\t<form>\r\n");
      out.write("\t\t\t    <ul data-role=\"listview\" data-inset=\"true\" data-theme=\"h\">\r\n");
      out.write("\t\t\t   \t\t<li data-role=\"list-divider\" data-theme=\"h\">ç»é²æ¸ã¿ã®æ¹</li>\t\r\n");
      out.write("\t\t\t        <li>\r\n");
      out.write("\t\t\t            <label for=\"name2\">ã­ã°ã¤ã³ï¼©ï¼¤</label>\r\n");
      out.write("\t\t\t            <input type=\"text\" name=\"name1\" id=\"name1\" value=\"\" data-clear-btn=\"true\">\r\n");
      out.write("\t\t\t        </li>\r\n");
      out.write("\t\t\t       <li>\r\n");
      out.write("\t\t\t            <label for=\"name2\">ãã¹ã¯ã¼ã</label>\r\n");
      out.write("\t\t\t            <input type=\"password\" name=\"name2\" id=\"name2\" value=\"\" data-clear-btn=\"true\">\r\n");
      out.write("\t\t\t        </li>\r\n");
      out.write("\t\t\t    </ul>\r\n");
      out.write("\t\t\t    <div style=\"height:30px;margin: 0 auto; width:100px;\">\r\n");
      out.write("\t\t\t \t\t<a href=\"top.html\" data-ajax=\"false\" data-role=\"button\" class=\" jqm-center-btn ui-btn ui-shadow ui-btn-corner-all ui-btn-up-i\" data-theme=\"i\">ã­ã°ã¤ã³</a>\r\n");
      out.write("\t\t\t \t</div>\r\n");
      out.write("\t\t\t \t<div style=\"margin-top:25px; margin-bottom:30px;\">\r\n");
      out.write("\t\t\t\t    <a href=\"#\" data-ajax=\"false\" style=\"text-decoration:underline;font-weight:normal;\">ã­ã°ã¤ã³ï¼©ï¼¤ããã¹ã¯ã¼ããå¿ããåºå</a>\r\n");
      out.write("\t\t\t \t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t   \t\t<form>\r\n");
      out.write("\t\t\t    <ul data-role=\"listview\" data-inset=\"true\" data-theme=\"h\">\r\n");
      out.write("\t\t\t    \t<li data-role=\"list-divider\" data-theme=\"h\">åãã¦ã®æ¹</li>\t\r\n");
      out.write("\t\t\t        <li>\r\n");
      out.write("\t\t\t            <label for=\"name2\">å¥è¨ºãã¼ã¿ï¼©ï¼¤</label>\r\n");
      out.write("\t\t\t            <table style=\"width:100%;\">\r\n");
      out.write("\t\t\t            \t<tr>\r\n");
      out.write("\t\t\t            \t\t<td>\r\n");
      out.write("\t\t\t            \t\t\t<input type=\"text\" name=\"name2\" id=\"name1\" value=\"\" data-clear-btn=\"true\">\r\n");
      out.write("\t\t\t            \t\t</td>\r\n");
      out.write("\t\t\t            \t\t<td>\r\n");
      out.write("\t\t\t            \t\t\t-\r\n");
      out.write("\t\t\t            \t\t</td>\r\n");
      out.write("\t\t\t            \t\t<td>\r\n");
      out.write("\t\t\t            \t\t\t <input type=\"text\" name=\"name2\" id=\"name2\" value=\"\" data-clear-btn=\"true\">\r\n");
      out.write("\t\t\t            \t\t</td>\r\n");
      out.write("\t\t\t            \t</tr>\r\n");
      out.write("\t\t\t            \t<tr>\r\n");
      out.write("\t\t\t            \t\t<td>\r\n");
      out.write("\t\t\t            \t\t\t<input type=\"text\" name=\"name2\" id=\"name3\" value=\"\" data-clear-btn=\"true\">\r\n");
      out.write("\t\t\t            \t\t</td>\r\n");
      out.write("\t\t\t            \t\t<td>\r\n");
      out.write("\t\t\t            \t\t\t-\r\n");
      out.write("\t\t\t            \t\t</td>\r\n");
      out.write("\t\t\t            \t\t<td>\r\n");
      out.write("\t\t\t            \t\t\t<input type=\"text\" name=\"name2\" id=\"name4\" value=\"\" data-clear-btn=\"true\">\r\n");
      out.write("\t\t\t            \t\t</td>\r\n");
      out.write("\t\t\t            \t</tr>\r\n");
      out.write("\t\t\t            </table>\r\n");
      out.write("\t\t\t        </li>\r\n");
      out.write("\t\t\t       <li>\r\n");
      out.write("\t\t\t            <label for=\"name2\">å¥è¨ºãã¼ã¿ãã¹ã¯ã¼ã</label>\r\n");
      out.write("\t\t\t            <input type=\"text\" name=\"name2\" id=\"name2\" value=\"\" data-clear-btn=\"true\">\r\n");
      out.write("\t\t\t        </li>\r\n");
      out.write("\t\t\t    </ul>\r\n");
      out.write("\t\t\t    <div style=\"height:30px;height:30px;margin: 0 auto; width:100px;\">\r\n");
      out.write("\t\t\t \t\t<a href=\"loginagreement.html\" data-ajax=\"false\" data-role=\"button\" class=\" jqm-center-btn ui-btn ui-shadow ui-btn-corner-all ui-btn-up-i\" data-theme=\"i\">æ¬¡ã¸</a>\r\n");
      out.write("\t\t\t \t</div>\r\n");
      out.write("\t\t\t \t<div style=\"margin-top:25px; margin-bottom:30px;\">\r\n");
      out.write("\t\t\t\t    <a href=\"#\" data-ajax=\"false\" style=\"text-decoration:underline;font-weight:normal;\">PCãµã¤ãã¸</a>\r\n");
      out.write("\t\t\t \t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("   \t\t</div>\r\n");
      out.write("   \t\t<div data-role='footer' class=\"jqm-footer\">\r\n");
      out.write("   \t\t\t<p>Â© Copyright 2013</p>\r\n");
      out.write("   \t\t</div> \t\r\n");
      out.write("   \t</div>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
