/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.54
 * Generated at: 2014-09-22 00:35:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.fileUpload;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class highcharts_005ftest_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("\t\t<title>Highcharts Example</title>\r\n");
      out.write("\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"./js/jquery.min.js\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t<LINK rel=\"stylesheet\" type=\"text/css\" href=\"./css/demo.css\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("$(function () {\r\n");
      out.write("        $('#container').highcharts({\r\n");
      out.write("            title: {\r\n");
      out.write("                text: 'Monthly Average Temperature',\r\n");
      out.write("                x: -20 //center\r\n");
      out.write("            },\r\n");
      out.write("            subtitle: {\r\n");
      out.write("                text: 'Source: WorldClimate.com',\r\n");
      out.write("                x: -20\r\n");
      out.write("            },\r\n");
      out.write("            xAxis: {\r\n");
      out.write("                categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',\r\n");
      out.write("                    'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']\r\n");
      out.write("            },\r\n");
      out.write("            yAxis: {\r\n");
      out.write("                title: {\r\n");
      out.write("                    text: 'Temperature (°C)'\r\n");
      out.write("                },\r\n");
      out.write("                plotLines: [{\r\n");
      out.write("                    value: 0,\r\n");
      out.write("                    width: 1,\r\n");
      out.write("                    color: '#808080'\r\n");
      out.write("                }]\r\n");
      out.write("            },\r\n");
      out.write("            tooltip: {\r\n");
      out.write("                valueSuffix: '°C'\r\n");
      out.write("            },\r\n");
      out.write("            legend: {\r\n");
      out.write("                layout: 'vertical',\r\n");
      out.write("                align: 'right',\r\n");
      out.write("                verticalAlign: 'middle',\r\n");
      out.write("                borderWidth: 0\r\n");
      out.write("            },\r\n");
      out.write("            series: [{\r\n");
      out.write("                name: 'Tokyo',\r\n");
      out.write("                data: [7.0, 6.9, 9.5, 14.5, 18.2, 21.5, 25.2, 26.5, 23.3, 18.3, 13.9, 9.6]\r\n");
      out.write("            }, {\r\n");
      out.write("                name: 'New York',\r\n");
      out.write("                data: [-0.2, 0.8, 5.7, 11.3, 17.0, 22.0, 24.8, 24.1, 20.1, 14.1, 8.6, 2.5]\r\n");
      out.write("            }, {\r\n");
      out.write("                name: 'Berlin',\r\n");
      out.write("                data: [-0.9, 0.6, 3.5, 8.4, 13.5, 17.0, 18.6, 17.9, 14.3, 9.0, 3.9, 1.0]\r\n");
      out.write("            }, {\r\n");
      out.write("                name: 'London',\r\n");
      out.write("                data: [3.9, 4.2, 5.7, 8.5, 11.9, 15.2, 17.0, 16.6, 14.2, 10.3, 6.6, 4.8]\r\n");
      out.write("            }]\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("<script src=\"./js/highcharts/highcharts.js\"></script>\r\n");
      out.write("<script src=\"./js/highcharts/exporting.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<div id=\"container\" style=\"min-width: 310px; height: 400px; margin: 0 auto\"></div>\r\n");
      out.write("\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
